package com.physiovertex.app

import android.app.Activity
import android.os.Bundle
import android.graphics.*
import android.text.InputType
import android.view.Gravity
import android.widget.*
import android.content.Intent
import android.provider.MediaStore
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class MainActivity : Activity() {
 private val blue=Color.rgb(24,92,180); private val prefs by lazy{getSharedPreferences("physiovertex",MODE_PRIVATE)}; private lateinit var root:LinearLayout; private var currentEmployee="PV001"
 override fun onCreate(b:Bundle?){super.onCreate(b);if(!prefs.contains("emp_PV001_pass"))prefs.edit().putString("emp_PV001_name","Employee 1").putString("emp_PV001_pass","1234").putString("emp_PV001_salary","0").apply();role()}
 private fun base():LinearLayout{val s=ScrollView(this);root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(48,56,48,56);setBackgroundColor(Color.rgb(245,249,255))};s.addView(root);setContentView(s);return root}
 private fun title(t:String)=TextView(this).apply{text=t;textSize=28f;setTextColor(blue);setTypeface(null,Typeface.BOLD);gravity=Gravity.CENTER;setPadding(0,20,0,28)}
 private fun label(t:String)=TextView(this).apply{text=t;textSize=17f;setTextColor(Color.DKGRAY);setPadding(4,14,4,8)}
 private fun edit(h:String,p:Boolean=false)=EditText(this).apply{hint=h;if(p)inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD}
 private fun btn(t:String,a:()->Unit)=Button(this).apply{text=t;textSize=17f;setTextColor(Color.WHITE);setBackgroundColor(blue);setOnClickListener{a()}}
 private fun sp()=Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,22)}
 private fun ids()=prefs.all.keys.filter{it.startsWith("emp_")&&it.endsWith("_pass")}.map{it.removePrefix("emp_").removeSuffix("_pass")}.distinct().sorted()
 private fun today()=SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(Date())
 private fun role(){val v=base();v.addView(title("PhysioVertex v4.2 Front Selfie"));v.addView(btn("EMPLOYEE LOGIN"){empLogin()});v.addView(sp());v.addView(btn("ADMIN LOGIN"){adminLogin()})}
 private fun empLogin(){val v=base();v.addView(title("Employee Login"));val id=edit("Employee ID");val p=edit("Password",true);v.addView(id);v.addView(p);v.addView(btn("LOGIN"){val e=id.text.toString().trim().uppercase(Locale.getDefault());if(prefs.getString("emp_${e}_pass",null)==p.text.toString()){currentEmployee=e;empDash()}else Toast.makeText(this,"Invalid login",Toast.LENGTH_SHORT).show()});v.addView(btn("BACK"){role()})}
 private fun adminLogin(){val v=base();v.addView(title("Admin Login"));val id=edit("Admin ID");val p=edit("Password",true);v.addView(id);v.addView(p);v.addView(label("Default: ADMIN / 2468"));v.addView(btn("LOGIN"){if(id.text.toString().trim().equals("ADMIN",true)&&p.text.toString()=="2468")adminDash()else Toast.makeText(this,"Invalid Admin Login",Toast.LENGTH_SHORT).show()});v.addView(btn("BACK"){role()})}
 private fun adminDash(){val v=base();v.addView(title("Admin Dashboard v4.2"));v.addView(btn("MY EMPLOYEE DASHBOARD"){currentEmployee="PV001";empDash()});v.addView(sp());v.addView(btn("ADD / UPDATE EMPLOYEE"){editor()});v.addView(sp());v.addView(btn("EMPLOYEE LIST / DELETE"){empList()});v.addView(sp());v.addView(btn("ATTENDANCE OVERVIEW"){attendance()});v.addView(sp());v.addView(btn("LEAVE REQUESTS"){adminLeaves()});v.addView(sp());v.addView(btn("LOGOUT"){role()})}
 private fun editor(){val v=base();v.addView(title("Add / Update Employee"));val id=edit("Employee ID e.g. PV002");val n=edit("Employee Name");val p=edit("Password",true);val sal=edit("Monthly Salary");sal.inputType=InputType.TYPE_CLASS_NUMBER;v.addView(id);v.addView(n);v.addView(p);v.addView(sal);v.addView(btn("SAVE EMPLOYEE"){val e=id.text.toString().trim().uppercase(Locale.getDefault());if(e.isBlank()||n.text.toString().isBlank()||p.text.toString().isBlank())Toast.makeText(this,"ID, Name and Password required",Toast.LENGTH_SHORT).show()else if(!prefs.contains("emp_${e}_pass")&&ids().size>=10)Toast.makeText(this,"Maximum 10 employees allowed",Toast.LENGTH_SHORT).show()else{prefs.edit().putString("emp_${e}_name",n.text.toString().trim()).putString("emp_${e}_pass",p.text.toString()).putString("emp_${e}_salary",sal.text.toString().ifBlank{"0"}).apply();adminDash()}});v.addView(btn("BACK"){adminDash()})}
 private fun empList(){val v=base();v.addView(title("Employee List"));ids().forEach{id->v.addView(label("$id - ${prefs.getString("emp_${id}_name","")} | Salary ₹${prefs.getString("emp_${id}_salary","0")}"));if(id!="PV001")v.addView(btn("DELETE $id"){prefs.edit().remove("emp_${id}_name").remove("emp_${id}_pass").remove("emp_${id}_salary").apply();empList()})};v.addView(btn("BACK"){adminDash()})}
 private fun empDash(){val v=base();v.addView(title("Employee Dashboard v4.2"));v.addView(label("${prefs.getString("emp_${currentEmployee}_name",currentEmployee)} ($currentEmployee)"));v.addView(label("Front-camera selfie required for Check-In and Check-Out\nLocation verification: will be added later"));val d=today();v.addView(label("Today\nIN: ${prefs.getString("in_${currentEmployee}_$d",null)?:"Not marked"}\nOUT: ${prefs.getString("out_${currentEmployee}_$d",null)?:"Not marked"}"));v.addView(btn("CHECK IN WITH SELFIE"){if(prefs.contains("in_${currentEmployee}_$d"))Toast.makeText(this,"Already checked in",Toast.LENGTH_SHORT).show()else camera("IN")});v.addView(sp());v.addView(btn("CHECK OUT WITH SELFIE"){if(!prefs.contains("in_${currentEmployee}_$d"))Toast.makeText(this,"Check in first",Toast.LENGTH_SHORT).show()else if(prefs.contains("out_${currentEmployee}_$d"))Toast.makeText(this,"Already checked out",Toast.LENGTH_SHORT).show()else camera("OUT")});v.addView(sp());v.addView(btn("ATTENDANCE HISTORY"){history()});v.addView(sp());v.addView(btn("SALARY DETAILS"){salary()});v.addView(sp());v.addView(btn("LEAVE REQUEST"){leave()});v.addView(sp());v.addView(btn("LOGOUT"){role()})}
 private fun camera(type:String){try{val i=Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra("android.intent.extras.CAMERA_FACING",1);i.putExtra("android.intent.extra.USE_FRONT_CAMERA",true);i.putExtra("android.intent.extras.LENS_FACING_FRONT",1);startActivityForResult(i,if(type=="IN")501 else 502)}catch(e:Exception){Toast.makeText(this,"Camera unavailable",Toast.LENGTH_SHORT).show()}}
 override fun onActivityResult(req:Int,res:Int,data:Intent?){super.onActivityResult(req,res,data);if(res!=RESULT_OK)return;val bmp=data?.extras?.get("data") as? Bitmap?:return;val type=if(req==501)"IN" else if(req==502)"OUT" else return;val d=today();val f=File(filesDir,"selfie_${currentEmployee}_${d}_${type}.jpg");FileOutputStream(f).use{bmp.compress(Bitmap.CompressFormat.JPEG,90,it)};val t=SimpleDateFormat("hh:mm a",Locale.getDefault()).format(Date());val e=prefs.edit().putString("selfie_${type.lowercase()}_${currentEmployee}_$d",f.absolutePath);if(type=="IN")e.putString("in_${currentEmployee}_$d",t).putLong("inms_${currentEmployee}_$d",System.currentTimeMillis())else e.putString("out_${currentEmployee}_$d",t).putLong("outms_${currentEmployee}_$d",System.currentTimeMillis());e.apply();Toast.makeText(this,"$type attendance saved with selfie",Toast.LENGTH_SHORT).show();empDash()}
 private fun image(path:String?):ImageView?{if(path.isNullOrBlank()||!File(path).exists())return null;return ImageView(this).apply{setImageBitmap(BitmapFactory.decodeFile(path));adjustViewBounds=true;maxHeight=450}}
 private fun attendance(){val v=base();v.addView(title("Attendance Overview + Selfies"));val d=today();ids().forEach{id->val im=prefs.getLong("inms_${id}_$d",0);val om=prefs.getLong("outms_${id}_$d",0);val w=if(im>0&&om>=im){val m=(om-im)/60000;"${m/60}h ${m%60}m"}else "-";v.addView(label("$id - ${prefs.getString("emp_${id}_name","")}\nIN: ${prefs.getString("in_${id}_$d",null)?:"-"} OUT: ${prefs.getString("out_${id}_$d",null)?:"-"}\nWORKED: $w"));image(prefs.getString("selfie_in_${id}_$d",null))?.let{v.addView(label("Check-In Selfie"));v.addView(it)};image(prefs.getString("selfie_out_${id}_$d",null))?.let{v.addView(label("Check-Out Selfie"));v.addView(it)}};v.addView(btn("BACK"){adminDash()})}
 private fun leave(){val v=base();v.addView(title("Leave Request"));val date=edit("Leave date");val reason=edit("Reason");v.addView(date);v.addView(reason);v.addView(btn("SUBMIT REQUEST"){if(date.text.toString().isBlank()||reason.text.toString().isBlank())Toast.makeText(this,"Date and reason required",Toast.LENGTH_SHORT).show()else{prefs.edit().putString("leave_${currentEmployee}_${System.currentTimeMillis()}","${date.text}|${reason.text}|PENDING").apply();empDash()}});v.addView(btn("BACK"){empDash()})}
 private fun leaves()=prefs.all.keys.filter{it.startsWith("leave_")}.sortedDescending()
 private fun adminLeaves(){val v=base();v.addView(title("Leave Requests"));if(leaves().isEmpty())v.addView(label("No leave requests"));leaves().forEach{k->val p=(prefs.getString(k,"")?:"").split("|");val id=k.removePrefix("leave_").substringBefore("_");val date=p.getOrElse(0){""};val r=p.getOrElse(1){""};val st=p.getOrElse(2){"PENDING"};v.addView(label("$id\nDate: $date\nReason: $r\nStatus: $st"));if(st=="PENDING"){v.addView(btn("APPROVE"){prefs.edit().putString(k,"$date|$r|APPROVED").apply();adminLeaves()});v.addView(btn("REJECT"){prefs.edit().putString(k,"$date|$r|REJECTED").apply();adminLeaves()})}};v.addView(btn("BACK"){adminDash()})}
 private fun history(){val v=base();v.addView(title("Attendance History"));val df=SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());val cal=Calendar.getInstance();repeat(30){val k=df.format(cal.time);val i=prefs.getString("in_${currentEmployee}_$k",null);val o=prefs.getString("out_${currentEmployee}_$k",null);if(i!=null||o!=null)v.addView(label("$k  IN: ${i?:"-"}  OUT: ${o?:"-"}"));cal.add(Calendar.DAY_OF_YEAR,-1)};v.addView(btn("BACK"){empDash()})}
 private fun salary(){val v=base();v.addView(title("Salary Details"));v.addView(label("Employee: $currentEmployee\nMonthly Salary: ₹${prefs.getString("emp_${currentEmployee}_salary","0")}"));v.addView(btn("BACK"){empDash()})}
}
