package com.physiovertex.app

import android.app.Activity
import android.os.Bundle
import android.graphics.*
import android.graphics.drawable.GradientDrawable
import android.text.InputType
import android.view.Gravity
import android.view.ViewGroup
import android.widget.*
import android.content.Intent
import android.provider.MediaStore
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

class MainActivity : Activity() {
 private val navy=Color.rgb(19,42,76)
 private val blue=Color.rgb(36,105,181)
 private val pale=Color.rgb(244,248,253)
 private val ink=Color.rgb(42,55,72)
 private val line=Color.rgb(218,229,242)
 private val prefs by lazy{getSharedPreferences("physiovertex",MODE_PRIVATE)}
 private lateinit var root:LinearLayout
 private var currentEmployee="PV001"
 override fun onCreate(b:Bundle?){super.onCreate(b);if(!prefs.contains("emp_PV001_pass"))prefs.edit().putString("emp_PV001_name","Employee 1").putString("emp_PV001_pass","1234").putString("emp_PV001_salary","0").apply();role()}
 private fun bg(color:Int,r:Float=24f,stroke:Int?=null)=GradientDrawable().apply{setColor(color);cornerRadius=r;if(stroke!=null)setStroke(2,stroke)}
 private fun base(center:Boolean=false):LinearLayout{val s=ScrollView(this).apply{setBackgroundColor(pale);isFillViewport=true};root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(38,48,38,52);if(center)gravity=Gravity.CENTER_VERTICAL};s.addView(root,ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.MATCH_PARENT));setContentView(s);return root}
 private fun brand(v:LinearLayout,subtitle:String){val b=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(18,16,18,20);background=bg(Color.WHITE,30f,line);elevation=5f};b.addView(ImageView(this).apply{setImageResource(R.drawable.physiovertex_logo);adjustViewBounds=true;scaleType=ImageView.ScaleType.CENTER_INSIDE},LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,180));b.addView(TextView(this).apply{text=subtitle.uppercase(Locale.getDefault());textSize=12f;letterSpacing=.08f;setTypeface(null,Typeface.BOLD);setTextColor(navy);gravity=Gravity.CENTER;setPadding(0,8,0,0)});v.addView(b,LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT));v.addView(sp(24))}
 private fun title(t:String)=TextView(this).apply{text=t.uppercase(Locale.getDefault());textSize=23f;letterSpacing=.04f;setTextColor(navy);setTypeface(null,Typeface.BOLD);gravity=Gravity.CENTER;setPadding(4,10,4,22)}
 private fun label(t:String)=TextView(this).apply{text=t;textSize=16f;setTextColor(ink);setPadding(24,20,24,20);background=bg(Color.WHITE,22f,line);elevation=2f}
 private fun edit(h:String,p:Boolean=false)=EditText(this).apply{hint=h.uppercase(Locale.getDefault());textSize=15f;setTextColor(ink);setHintTextColor(Color.rgb(116,132,151));setPadding(22,8,22,8);background=bg(Color.WHITE,18f,line);if(p)inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD;layoutParams=LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,60).apply{setMargins(0,7,0,7)}}
 private fun btn(t:String,a:()->Unit)=Button(this).apply{text=t.uppercase(Locale.getDefault());textSize=14f;letterSpacing=.05f;setTextColor(Color.WHITE);setTypeface(null,Typeface.BOLD);isAllCaps=true;background=bg(blue,24f);elevation=5f;minHeight=60;setPadding(16,8,16,8);setOnClickListener{a()}}
 private fun backBtn(t:String="Back",a:()->Unit)=Button(this).apply{text=t.uppercase(Locale.getDefault());textSize=14f;letterSpacing=.05f;setTextColor(navy);setTypeface(null,Typeface.BOLD);isAllCaps=true;background=bg(Color.WHITE,24f,blue);elevation=2f;minHeight=56;setOnClickListener{a()}}
 private fun sp(h:Int=18)=Space(this).apply{layoutParams=LinearLayout.LayoutParams(1,h)}
 private fun ids()=prefs.all.keys.filter{it.startsWith("emp_")&&it.endsWith("_pass")}.map{it.removePrefix("emp_").removeSuffix("_pass")}.distinct().sorted()
 private fun today()=SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(Date())
 private fun role(){val v=base(true);brand(v,"Employee Attendance & Management");v.addView(title("Team Portal"));v.addView(btn("Employee Login"){empLogin()});v.addView(sp());v.addView(btn("Admin Login"){adminLogin()});v.addView(sp(28));v.addView(TextView(this).apply{text="MOBILITY MADE MAGICAL";gravity=Gravity.CENTER;textSize=12f;letterSpacing=.12f;setTypeface(null,Typeface.BOLD);setTextColor(blue)})}
 private fun empLogin(){val v=base(true);brand(v,"Employee Portal");v.addView(title("Employee Login"));val id=edit("Employee ID");val p=edit("Password",true);v.addView(id);v.addView(p);v.addView(sp());v.addView(btn("Login"){val e=id.text.toString().trim().uppercase(Locale.getDefault());if(prefs.getString("emp_${e}_pass",null)==p.text.toString()){currentEmployee=e;empDash()}else Toast.makeText(this,"Invalid login",Toast.LENGTH_SHORT).show()});v.addView(sp());v.addView(backBtn{role()})}
 private fun adminLogin(){val v=base(true);brand(v,"Administration");v.addView(title("Admin Login"));val id=edit("Admin ID");val p=edit("Password",true);v.addView(id);v.addView(p);v.addView(sp(8));v.addView(TextView(this).apply{text="ADMIN ACCESS";textSize=12f;letterSpacing=.08f;setTypeface(null,Typeface.BOLD);setTextColor(Color.GRAY);gravity=Gravity.CENTER});v.addView(sp());v.addView(btn("Login"){if(id.text.toString().trim().equals("ADMIN",true)&&p.text.toString()=="2468")adminDash()else Toast.makeText(this,"Invalid Admin Login",Toast.LENGTH_SHORT).show()});v.addView(sp());v.addView(backBtn{role()})}
 private fun adminDash(){val v=base(true);brand(v,"PhysioVertex Team Portal");v.addView(title("Admin Dashboard"));v.addView(btn("My Employee Dashboard"){currentEmployee="PV001";empDash()});v.addView(sp());v.addView(btn("Add / Update Employee"){editor()});v.addView(sp());v.addView(btn("Employee List / Delete"){empList()});v.addView(sp());v.addView(btn("Attendance Overview"){attendance()});v.addView(sp());v.addView(btn("Leave Requests"){adminLeaves()});v.addView(sp(24));v.addView(backBtn("Logout"){role()})}
 private fun editor(){val v=base();brand(v,"Staff Management");v.addView(title("Add / Update Employee"));val id=edit("Employee ID e.g. PV002");val n=edit("Employee Name");val p=edit("Password",true);val sal=edit("Monthly Salary");sal.inputType=InputType.TYPE_CLASS_NUMBER;v.addView(id);v.addView(n);v.addView(p);v.addView(sal);v.addView(sp());v.addView(btn("Save Employee"){val e=id.text.toString().trim().uppercase(Locale.getDefault());if(e.isBlank()||n.text.toString().isBlank()||p.text.toString().isBlank())Toast.makeText(this,"ID, Name and Password required",Toast.LENGTH_SHORT).show()else if(!prefs.contains("emp_${e}_pass")&&ids().size>=10)Toast.makeText(this,"Maximum 10 employees allowed",Toast.LENGTH_SHORT).show()else{prefs.edit().putString("emp_${e}_name",n.text.toString().trim()).putString("emp_${e}_pass",p.text.toString()).putString("emp_${e}_salary",sal.text.toString().ifBlank{"0"}).apply();adminDash()}});v.addView(sp());v.addView(backBtn{adminDash()})}
 private fun empList(){val v=base();brand(v,"Staff Directory");v.addView(title("Employee List"));ids().forEach{id->v.addView(label("$id  •  ${prefs.getString("emp_${id}_name","")}\nMonthly Salary: ₹${prefs.getString("emp_${id}_salary","0")}"));v.addView(sp(10));if(id!="PV001"){v.addView(backBtn("Delete $id"){prefs.edit().remove("emp_${id}_name").remove("emp_${id}_pass").remove("emp_${id}_salary").apply();empList()});v.addView(sp())}};v.addView(backBtn{adminDash()})}
 private fun empDash(){val v=base();brand(v,"Employee Attendance");v.addView(title("Welcome, ${prefs.getString("emp_${currentEmployee}_name",currentEmployee)}"));v.addView(label("Employee ID: $currentEmployee\nFront-camera selfie required for Check-In and Check-Out\nLocation verification will be added later"));v.addView(sp());val d=today();v.addView(label("TODAY\nCheck-In: ${prefs.getString("in_${currentEmployee}_$d",null)?:"Not marked"}\nCheck-Out: ${prefs.getString("out_${currentEmployee}_$d",null)?:"Not marked"}"));v.addView(sp());v.addView(btn("Check In with Selfie"){if(prefs.contains("in_${currentEmployee}_$d"))Toast.makeText(this,"Already checked in",Toast.LENGTH_SHORT).show()else camera("IN")});v.addView(sp());v.addView(btn("Check Out with Selfie"){if(!prefs.contains("in_${currentEmployee}_$d"))Toast.makeText(this,"Check in first",Toast.LENGTH_SHORT).show()else if(prefs.contains("out_${currentEmployee}_$d"))Toast.makeText(this,"Already checked out",Toast.LENGTH_SHORT).show()else camera("OUT")});v.addView(sp());v.addView(btn("Attendance History"){history()});v.addView(sp());v.addView(btn("Salary Details"){salary()});v.addView(sp());v.addView(btn("Leave Request"){leave()});v.addView(sp(24));v.addView(backBtn("Logout"){role()})}
 private fun camera(type:String){try{val i=Intent(MediaStore.ACTION_IMAGE_CAPTURE);i.putExtra("android.intent.extras.CAMERA_FACING",1);i.putExtra("android.intent.extra.USE_FRONT_CAMERA",true);i.putExtra("android.intent.extras.LENS_FACING_FRONT",1);startActivityForResult(i,if(type=="IN")501 else 502)}catch(e:Exception){Toast.makeText(this,"Camera unavailable",Toast.LENGTH_SHORT).show()}}
 override fun onActivityResult(req:Int,res:Int,data:Intent?){super.onActivityResult(req,res,data);if(res!=RESULT_OK)return;val bmp=data?.extras?.get("data") as? Bitmap?:return;val type=if(req==501)"IN" else if(req==502)"OUT" else return;val d=today();val f=File(filesDir,"selfie_${currentEmployee}_${d}_${type}.jpg");FileOutputStream(f).use{bmp.compress(Bitmap.CompressFormat.JPEG,90,it)};val t=SimpleDateFormat("hh:mm a",Locale.getDefault()).format(Date());val e=prefs.edit().putString("selfie_${type.lowercase()}_${currentEmployee}_$d",f.absolutePath);if(type=="IN")e.putString("in_${currentEmployee}_$d",t).putLong("inms_${currentEmployee}_$d",System.currentTimeMillis())else e.putString("out_${currentEmployee}_$d",t).putLong("outms_${currentEmployee}_$d",System.currentTimeMillis());e.apply();Toast.makeText(this,"$type attendance saved with selfie",Toast.LENGTH_SHORT).show();empDash()}
 private fun image(path:String?):ImageView?{if(path.isNullOrBlank()||!File(path).exists())return null;return ImageView(this).apply{setImageBitmap(BitmapFactory.decodeFile(path));adjustViewBounds=true;maxHeight=450;background=bg(Color.WHITE,22f);setPadding(8,8,8,8)}}
 private fun attendance(){val v=base();brand(v,"Attendance Control");v.addView(title("Attendance Overview"));val d=today();ids().forEach{id->val im=prefs.getLong("inms_${id}_$d",0);val om=prefs.getLong("outms_${id}_$d",0);val w=if(im>0&&om>=im){val m=(om-im)/60000;"${m/60}h ${m%60}m"}else "-";v.addView(label("$id  •  ${prefs.getString("emp_${id}_name","")}\nIN: ${prefs.getString("in_${id}_$d",null)?:"-"}   OUT: ${prefs.getString("out_${id}_$d",null)?:"-"}\nWorked: $w"));image(prefs.getString("selfie_in_${id}_$d",null))?.let{v.addView(sp(8));v.addView(it)};image(prefs.getString("selfie_out_${id}_$d",null))?.let{v.addView(sp(8));v.addView(it)};v.addView(sp())};v.addView(backBtn{adminDash()})}
 private fun leave(){val v=base();brand(v,"Employee Leave");v.addView(title("Leave Request"));val date=edit("Leave date");val reason=edit("Reason");v.addView(date);v.addView(reason);v.addView(sp());v.addView(btn("Submit Request"){if(date.text.toString().isBlank()||reason.text.toString().isBlank())Toast.makeText(this,"Date and reason required",Toast.LENGTH_SHORT).show()else{prefs.edit().putString("leave_${currentEmployee}_${System.currentTimeMillis()}","${date.text}|${reason.text}|PENDING").apply();empDash()}});v.addView(sp());v.addView(backBtn{empDash()})}
 private fun leaves()=prefs.all.keys.filter{it.startsWith("leave_")}.sortedDescending()
 private fun adminLeaves(){val v=base();brand(v,"Leave Management");v.addView(title("Leave Requests"));if(leaves().isEmpty())v.addView(label("No leave requests"));leaves().forEach{k->val p=(prefs.getString(k,"")?:"").split("|");val id=k.removePrefix("leave_").substringBefore("_");val date=p.getOrElse(0){""};val r=p.getOrElse(1){""};val st=p.getOrElse(2){"PENDING"};v.addView(label("$id  •  ${prefs.getString("emp_${id}_name",id)}\nDate: $date\nReason: $r\nStatus: $st"));v.addView(sp(8));if(st=="PENDING"){v.addView(btn("Approve"){prefs.edit().putString(k,"$date|$r|APPROVED").apply();adminLeaves()});v.addView(sp(8));v.addView(backBtn("Reject"){prefs.edit().putString(k,"$date|$r|REJECTED").apply();adminLeaves()})};v.addView(sp())};v.addView(backBtn{adminDash()})}
 private fun history(){val v=base();brand(v,"Attendance Records");v.addView(title("Attendance History"));val df=SimpleDateFormat("yyyy-MM-dd",Locale.getDefault());val cal=Calendar.getInstance();repeat(30){val k=df.format(cal.time);val i=prefs.getString("in_${currentEmployee}_$k",null);val o=prefs.getString("out_${currentEmployee}_$k",null);if(i!=null||o!=null){v.addView(label("$k\nIN: ${i?:"-"}   OUT: ${o?:"-"}"));v.addView(sp(10))};cal.add(Calendar.DAY_OF_YEAR,-1)};v.addView(backBtn{empDash()})}
 private fun salary(){val v=base();brand(v,"Employee Payroll");v.addView(title("Salary Details"));v.addView(label("Employee: ${prefs.getString("emp_${currentEmployee}_name",currentEmployee)}\nID: $currentEmployee\nMonthly Salary: ₹${prefs.getString("emp_${currentEmployee}_salary","0")}"));v.addView(sp());v.addView(backBtn{empDash()})}
}
